/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/JCFrQEVOKGa
 */
import { Button } from "@/components/ui/button"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Checkbox } from "@/components/ui/checkbox"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Badge } from "@/components/ui/badge"

export function Dashboard() {
  return (
    <div className="bg-white p-8">
      <div className="flex flex-col space-y-6">
        <div className="flex justify-between">
          <h1 className="text-2xl font-bold">CAIQ</h1>
          <div className="flex space-x-4">
            <Button variant="ghost">Sandbox</Button>
            <Avatar>
              <AvatarImage alt="User avatar" src="/placeholder.svg?height=32&width=32" />
              <AvatarFallback>U</AvatarFallback>
            </Avatar>
          </div>
        </div>
        <div className="flex space-x-6">
          <Button variant="outline">Meta</Button>
          <Button variant="outline">Manage</Button>
          <Button variant="outline">Respond</Button>
          <Button variant="outline">Review</Button>
          <Button variant="outline">Progress</Button>
          <Button variant="outline">Supporting Documentation</Button>
          <Button variant="outline">Export</Button>
        </div>
        <div className="flex justify-between">
          <div className="flex space-x-4">
            <Button variant="secondary">
              <MenuIcon className="text-gray-500" />
            </Button>
            <Input placeholder="Search..." />
          </div>
          <div className="flex space-x-2">
            <Button variant="secondary">Owners (2)</Button>
            <Button variant="secondary">Status (4)</Button>
            <Button variant="default">+ Add Questions</Button>
          </div>
        </div>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="w-[50%]">QUESTION</TableHead>
              <TableHead className="w-[25%]">ASSIGNED TO</TableHead>
              <TableHead className="w-[15%]">STATUS</TableHead>
              <TableHead className="w-[10%]">DUE</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell>
                <div className="flex items-center space-x-2">
                  <Checkbox id="q1" />
                  <label className="flex-1" htmlFor="q1">
                    Audit & Assurance A&A-01.1 Are audit and assurance policies, procedures, and standards established,
                    documented, approved, communicated, applied, evaluated, and maintained?
                  </label>
                </div>
              </TableCell>
              <TableCell>
                <Select>
                  <SelectTrigger id="assigned-to-1">
                    <SelectValue placeholder="Henry Irish" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Henry Irish">Henry Irish</SelectItem>
                    <SelectItem value="John Doe">John Doe</SelectItem>
                    <SelectItem value="Jane Smith">Jane Smith</SelectItem>
                    <SelectItem value="Alice Johnson">Alice Johnson</SelectItem>
                    <SelectItem value="Bob Williams">Bob Williams</SelectItem>
                    <SelectItem value="Ella Brown">Ella Brown</SelectItem>
                    <SelectItem value="Mike Davis">Mike Davis</SelectItem>
                    <SelectItem value="Sarah Wilson">Sarah Wilson</SelectItem>
                    <SelectItem value="Tom Thompson">Tom Thompson</SelectItem>
                    <SelectItem value="Olivia Clark">Olivia Clark</SelectItem>
                    <SelectItem value="James Lee">James Lee</SelectItem>
                    <SelectItem value="Sophia Young">Sophia Young</SelectItem>
                    <SelectItem value="David Moore">David Moore</SelectItem>
                    <SelectItem value="Emma White">Emma White</SelectItem>
                    <SelectItem value="William Hall">William Hall</SelectItem>
                    <SelectItem value="Ava King">Ava King</SelectItem>
                    <SelectItem value="Michael Scott">Michael Scott</SelectItem>
                    <SelectItem value="Grace Adams">Grace Adams</SelectItem>
                    <SelectItem value="Ryan Baker">Ryan Baker</SelectItem>
                    <SelectItem value="Lily Green">Lily Green</SelectItem>
                  </SelectContent>
                </Select>
              </TableCell>
              <TableCell>
                <Badge variant="secondary">Complete</Badge>
              </TableCell>
              <TableCell>Nov 2, 2023</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                <div className="flex items-center space-x-2">
                  <Checkbox id="q2" />
                  <label className="flex-1" htmlFor="q2">
                    A&A-01.2 Are audit and assurance policies, procedures, and standards reviewed and updated at least
                    annually?
                  </label>
                </div>
              </TableCell>
              <TableCell>
                <Select>
                  <SelectTrigger id="assigned-to-2">
                    <SelectValue placeholder="Henry Irish" />
                  </SelectTrigger>
                </Select>
              </TableCell>
              <TableCell>
                <Badge variant="secondary">Complete</Badge>
              </TableCell>
              <TableCell>Nov 2, 2023</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                <div className="flex items-center space-x-2">
                  <Checkbox id="q3" />
                  <label className="flex-1" htmlFor="q3">
                    A&A-02.1 Are independent audit and assurance assessments conducted according to relevant standards
                    at least annually?
                  </label>
                </div>
              </TableCell>
              <TableCell>
                <Select>
                  <SelectTrigger id="assigned-to-3">
                    <SelectValue placeholder="Henry Irish" />
                  </SelectTrigger>
                </Select>
              </TableCell>
              <TableCell>
                <Badge variant="secondary">Complete</Badge>
              </TableCell>
              <TableCell>Nov 2, 2023</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                <div className="flex items-center space-x-2">
                  <Checkbox id="q4" />
                  <label className="flex-1" htmlFor="q4">
                    A&A-03.1 Are independent audit and assurance assessments performed according to risk-based plans and
                    policies?
                  </label>
                </div>
              </TableCell>
              <TableCell>
                <Select>
                  <SelectTrigger id="assigned-to-4">
                    <SelectValue placeholder="Henry Irish" />
                  </SelectTrigger>
                </Select>
              </TableCell>
              <TableCell>
                <Badge variant="secondary">Complete</Badge>
              </TableCell>
              <TableCell>Nov 2, 2023</TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    </div>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}
